export let projects = [
    {
      title: "Html & Css Project",
      category: ["html", "css"],
      description: "orem ipsum dolor sit amet",
      imgPath: "public/1.jpg",
      github: "http",
      demo: "http",
    },
    {
      title: "Javascript Project",
      category: ["html", "css", "javascript"],
      description: "orem ipsum dolor sit amet",
      imgPath: "public/1.jpg",
      github: "http",
      demo: "http",
    },
    {
      title: "Bootstrap Project",
      category: ["html", "bootstrap", "javascript"],
      description: "orem ipsum dolor sit amet",
      imgPath: "public/1.jpg",
      github: "http",
      demo: "http",
    },
    {
      title: "react Project",
      category: ["react", "mUI"],
      description: "orem ipsum dolor sit amet",
      imgPath: "public/1.jpg",
      github: "http",
      demo: "http",
    },
    {
      title: "React With Strapi Project",
      category: ["react", "mui", "strapi"],
      description: "orem ipsum dolor sit amet",
      imgPath: "public/1.jpg",
      github: "http",
      demo: "http",
    },
  ];